/vis/open OGL
/vis/drawVolume
/vis/viewer/set/viewpointVector 1 1 1
/vis/scene/add/axes 0 0 0 1500 mm
/vis/scene/add/line 0 0 0 1.500  1.500 0 
/vis/scene/add/arrow 0 0 0 1.500 1.500 0 
/run/beamOn 10000
/vis/viewer/set/autoRefresh true
/tracking/storeTrajectory 1
/vis/scene/add/trajectories
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set OpticalPhoton cyan